exclude: '^/migrations/|src/core/static|config/|\.html$|\.svg$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ "--fix" ]
        exclude: "migrations/"
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        exclude: "migrations/|tests/"

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.21.0
    hooks:
      - id: django-upgrade
        args: ["--target-version", "5.1"]
