services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: make backend-run
    container_name: spa_web
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: make frontend-run
    container_name: frontend-run
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  db:
    image: postgres:16-alpine
    container_name: spa_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  pgdata:
  static:
  media:
