# Generated by Django 6.1 on 2026-09-01 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="parent",
            new_name="comment_id",
        ),
        migrations.AddField(
            model_name="comments",
            name="file",
            field=models.FileField(
                default=1,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["txt", "jpg", "gif", "png"],
                        message="Разрешены только файлы формата TXT, JPG, GIF и PNG.",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
