# Generated by Django 6.1 on 2026-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='home_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
