# Generated by Django 6.1 on 2026-09-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
